infection_spread_simulation: infection_spread_simulation.o
	gcc infection_spread_simulation.o -o infection_spread_simulation

infection_spread_simulation.o: infection_spread_simulation.c
	gcc -g -Wall -Wshadow -c infection_spread_simulation.c
