main: map_grid_utilities.o main.o
	gcc map_grid_utilities.o main.o -o main

map_grid_utilities.o: map_grid_utilities.c
	gcc -g -Wall -Wshadow -c map_grid_utilities.c

main.o: main.c
	gcc -g -Wall -Wshadow -c main.c
